# WARNING - Generated by {fusen} from dev/flat_create_selectivity_sheet.Rmd: do not edit by hand

test_that("create_selectivity_sheet works in French", {
  # Create tmp folder
  output_dir <- tempfile(pattern = "inser")
  dir.create(output_dir)
  
  # Setup input OTT data
  OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTT_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")#,colClasses = colClasses)
  
  SL<-read.table(
    file.path(OTT_data_folder, "SL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  HL<-read.table(
    file.path(OTT_data_folder, "HL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    colClasses = colClasses,
    encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
  
  # Setup zone and min_length params
  min_length <- data.frame(species=unique(TAB$species),min_length=c(27,24,20,NA,27,NA))
  zones <- c("8.a","8.b","7.d","7.e","7.h")
  
  # run function for "twin" report
  #' @description Testing no error occur during the generation of the "twin" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_twin",
      protocol = "twin",
      language = "FR",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "twin" report from `create_selectivity_sheet()` is created
  #expect_true(file.exists(file.path(output_dir, "fiche_InseR_twin.docx")))
   expect_true(file.exists(file.path(output_dir, "fiche_InseR_twin.html")))
  
  # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_twin.docx"),
  #   exdir = file.path(output_dir, "unzip_twin")
  # )

  
  #' @description Testing all figures are present in the "twin" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_twin", "word", "media")
  #   ),
  #   28
  # )
  
    expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_twin_files/figure-html")
    ),
    28
  )
  
  
  # Setup OTB input data
  OTB_data_folder <- system.file("script_origin","Data","Example_OTB_alternate", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTB_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  HH<-read.table(file.path(OTB_data_folder, "HH.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")#,colClasses = colClasses)
  SL<-read.table(file.path(OTB_data_folder, "SL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  HL<-read.table(file.path(OTB_data_folder, "HL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(file.path(OTB_data_folder, "HH.csv"),sep=";",header=TRUE,colClasses = colClasses, encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB<-prep_sel_data(data=list(TR,HH,SL,HL))
  
  # run function for "paired" report
  #' @description Testing no error occur during the generation of the "paired" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_paired",
      protocol = "paired",
      language = "FR",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "paired" report from `create_selectivity_sheet()` is created
  #expect_true(file.exists(file.path(output_dir, "fiche_InseR_paired.docx")))
  expect_true(file.exists(file.path(output_dir, "fiche_InseR_paired.html")))
  
  # # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_paired.docx"),
  #   exdir = file.path(output_dir, "unzip_paired")
  # )
  # 
  # #' @description Testing all figures are present in the "paired" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_paired", "word", "media")
  #   ),
  #   28
  # )
  
      expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_paired_files/figure-html")
    ),
    28
  )
  
  # run function for "unpaired" report
  #' @description Testing no error occur during the generation of the "unpaired" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_unpaired",
      protocol = "unpaired",
      language = "FR",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "unpaired" report from `create_selectivity_sheet()` is created
  #expect_true(file.exists(file.path(output_dir, "fiche_InseR_unpaired.docx")))
   expect_true(file.exists(file.path(output_dir, "fiche_InseR_unpaired.html")))
  
  #  # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_unpaired.docx"),
  #   exdir = file.path(output_dir, "unzip_unpaired")
  # )
  # 
  # #' @description Testing all figures are present in the "unpaired" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_unpaired", "word", "media")
  #   ),
  #   28
  # )
      
   expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_unpaired_files/figure-html")
    ),
    28
  )
      
  # Clear tmp folder
  unlink(output_dir, recursive = TRUE)
})

test_that("create_selectivity_sheet works in English", {
  # Create tmp folder
  output_dir <- tempfile(pattern = "inser")
  dir.create(output_dir)
  
  # Setup input OTT data
  OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTT_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")#,colClasses = colClasses)
  
  SL<-read.table(
    file.path(OTT_data_folder, "SL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  HL<-read.table(
    file.path(OTT_data_folder, "HL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    colClasses = colClasses,
    encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
  
  # Setup zone and min_length params
  min_length <- data.frame(species=unique(TAB$species),min_length=c(27,24,20,NA,27,NA))
  zones <- c("8.a","8.b","7.d","7.e","7.h")
  
  # run function for "twin" report
  #' @description Testing no error occur during the generation of the "twin" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_twin",
      protocol = "twin",
      language = "EN",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "twin" report from `create_selectivity_sheet()` is created
  #expect_true(file.exists(file.path(output_dir, "fiche_InseR_twin.docx")))
   expect_true(file.exists(file.path(output_dir, "fiche_InseR_twin.html")))

  # # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_twin.docx"),
  #   exdir = file.path(output_dir, "unzip_twin")
  # )
  # 
     
  #' @description Testing all figures are present in the "twin" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_twin", "word", "media")
  #   ),
  #   28
  # )
    expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_twin_files/figure-html")
    ),
    28
  )
  
  # Setup OTB input data
  OTB_data_folder <- system.file("script_origin","Data","Example_OTB_alternate", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTB_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  HH<-read.table(file.path(OTB_data_folder, "HH.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")#,colClasses = colClasses)
  SL<-read.table(file.path(OTB_data_folder, "SL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  HL<-read.table(file.path(OTB_data_folder, "HL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(file.path(OTB_data_folder, "HH.csv"),sep=";",header=TRUE,colClasses = colClasses, encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB<-prep_sel_data(data=list(TR,HH,SL,HL))
  
  # run function for "paired" report
  #' @description Testing no error occur during the generation of the "paired" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_paired",
      protocol = "paired",
      language = "EN",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "paired" report from `create_selectivity_sheet()` is created
  expect_true(file.exists(file.path(output_dir, "fiche_InseR_paired.html")))
  
  # # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_paired.docx"),
  #   exdir = file.path(output_dir, "unzip_paired")
  # )
  # 
  # #' @description Testing all figures are present in the "paired" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_paired", "word", "media")
  #   ),
  #   28
  # )
      expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_paired_files/figure-html")
    ),
    28
  )
  
  # run function for "unpaired" report
  #' @description Testing no error occur during the generation of the "unpaired" report
  expect_error(
    create_selectivity_sheet(
      data = TAB,
      output_dir = output_dir,
      output_file = "fiche_InseR_unpaired",
      protocol = "unpaired",
      language = "EN",
      zones = zones,
      min_length = min_length
    ), 
    NA
  )
  
  #' @description Testing the "unpaired" report from `create_selectivity_sheet()` is created
  expect_true(file.exists(file.path(output_dir, "fiche_InseR_unpaired.html")))
  
  # # unzip doc to access figures and tables
  # unzip(
  #   zipfile = file.path(output_dir, "fiche_InseR_unpaired.docx"),
  #   exdir = file.path(output_dir, "unzip_unpaired")
  # )
  # 
  # #' @description Testing all figures are present in the "unpaired" report
  # expect_length(
  #   list.files(
  #     file.path(output_dir, "unzip_unpaired", "word", "media")
  #   ),
  #   28
  # )
      expect_length(
   list.files(
      file.path(output_dir, "fiche_InseR_unpaired_files/figure-html")
    ),
    28
  )
  
  # Clear tmp folder
  unlink(output_dir, recursive = TRUE)
})
