# WARNING - Generated by {fusen} from dev/flat_create_maps.Rmd: do not edit by hand

test_that("create_maps works", {
  # Setup input OTT data
  OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTT_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  HH<-read.table(file.path(OTT_data_folder, "HH.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")#,colClasses = colClasses)
  SL<-read.table(file.path(OTT_data_folder, "SL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  HL<-read.table(file.path(OTT_data_folder, "HL.csv"),sep=";",header=TRUE, encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(file.path(OTT_data_folder, "HH.csv"),sep=";",header=TRUE,colClasses = colClasses, encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
  
  # create maps
  output <- create_maps(
    zones = c("8.a","8.b","7.d","7.e","7.h"),
    protocol = "twin",
    data = TAB
  )
  
  #' @description Testing the class of the output from `create_maps`
  expect_s3_class(
    object = output,
    class = c("gg", "ggplot", "ggarrange")
  )
  
  #' @description Test case with non valid geometry (centroid)
  output_4c <- create_maps(data = TAB, zones = "4.c", protocol = "twin")
  
  expect_s3_class(
    object = output_4c,
    class = c("gg", "ggplot", "ggarrange")
  )
})

