# WARNING - Generated by {fusen} from /dev/flat_translate_selectivity_sheet.Rmd: do not edit by hand

test_that("create_translate_dict works", {

  # create csv with wrong extension
  output_dir <- tempfile(pattern = "translate_dict")
  dir.create(output_dir)
  file.copy(from = system.file("template", "translation.csv", package = "inser"),
            to = file.path(output_dir, "notacsvfile.txt"))
  bad_ext_file <- normalizePath(
    file.path(output_dir, "notacsvfile.txt"),
    winslash = "/"
  )
  
  #' @description Test `create_translate_dict` returns error for incorrect csv or language
  expect_error(
    object = create_translate_dict(path = "notaexistingfile"),
    regexp = "Translation file notaexistingfile not found"
    )
  expect_error(
    object = create_translate_dict(
      path = bad_ext_file
      ),
    regexp = glue::glue("Translation file {bad_ext_file} is not a csv file")
    )
  expect_error(
    object = create_translate_dict(
      language = "IT"
    ),
    regexp = "\\'arg\\' should be one of .EN., .FR."
  )
  
  # run function for EN and FR output (testing both upper and lower case)
  en_output <- create_translate_dict(language = "EN")
  fr_output <- create_translate_dict(language = "FR")
  
  #' @description Test english output of `create_translate_dict`
  expect_equal(object = en_output[["0_test_entry"]],
               expected = "This is the text output of the example entry")
  expect_equal(object = fr_output[["0_test_entry"]],
               expected = "Ceci est la sortie de texte de l'entrée d'exemple")
  
  # clean
  unlink(output_dir,recursive = TRUE)
})
