# WARNING - Generated by {fusen} from /dev/flat_utils.Rmd: do not edit by hand

test_that("f_test works", {

  # Setup OTB input data
  OTB_data_folder <-
    system.file("script_origin", "Data", "Example_OTB_alternate", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTB_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  HH <-
    read.table(
      file.path(OTB_data_folder, "HH.csv"),
      sep = ";",
      header = TRUE,
      encoding = "WINDOWS-1252"
    )#,colClasses = colClasses)
  SL <-
    read.table(
      file.path(OTB_data_folder, "SL.csv"),
      sep = ";",
      header = TRUE,
      encoding = "WINDOWS-1252"
    )
  HL <-
    read.table(
      file.path(OTB_data_folder, "HL.csv"),
      sep = ";",
      header = TRUE,
      encoding = "WINDOWS-1252"
    )
  
  colClasses <- rep(NA, ncol(HH))
  colClasses[which(names(HH) == "statistical_rectangle")] <-
    "character"
  
  HH <-
    read.table(
      file.path(OTB_data_folder, "HH.csv"),
      sep = ";",
      header = TRUE,
      colClasses = colClasses,
      encoding = "WINDOWS-1252"
    )
  
  # create TAB output
  data <- prep_sel_data(data = list(TR, HH, SL, HL))
  
  # weight for each species
  weight_species <-
    data %>% dplyr::group_by(
      project,
      vessel_identifier,
      trip_code,
      station_number,
      gear_label,
      catch_category,
      species
    ) %>%
    dplyr::summarize(weight = sum(weight) * 10 ^ (-3)) %>% as.data.frame()
  
  weight_species <-
    as.data.frame(
      tidyr::complete(
        weight_species,
        tidyr::nesting(project, vessel_identifier, trip_code, station_number),
        gear_label,
        catch_category,
        species,
        fill = list(weight = 0)
      )
    )
  
  # run f_test_unpaired
  ftest_solea_solea <- f_test_unpaired(weight_species = weight_species,
                  sp = "Solea solea",
                  cat = "LAN")
  
  
  #' @description Test f_test_unpaired returns the correct statistical values
  expect_equal(object = ftest_solea_solea,
               expected = structure(
                 list(
                   pvalue = 0.7052,
                   moyenne = -50.5571534874102,
                   mediane = 0,
                   test = "Kolmogorov",
                   Taux_Var_Tot = -82.21
                 ),
                 class = "data.frame",
                 row.names = c(NA,
                               -1L)
               ))
  
})
