# WARNING - Generated by {fusen} from /dev/flat_create_selectivity_sheet.Rmd: do not edit by hand

test_that("create_selectivity_sheet works", {
  # Create tmp folder
  output_dir <- tempfile(pattern = "inser")
  dir.create(output_dir)
  
  # Setup input OTT data
  OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTT_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")#,colClasses = colClasses)
  
  SL<-read.table(
    file.path(OTT_data_folder, "SL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  HL<-read.table(
    file.path(OTT_data_folder, "HL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    colClasses = colClasses,
    encoding = "WINDOWS-1252")
  
  # create TAB output
  TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
  
  # Setup zone and min_length params
  min_length <- data.frame(species=unique(TAB$species),min_length=c(27,24,20,NA,27,NA))
  zones <- c("8.a","8.b","7.d","7.e","7.h")
  
  # run function
  create_selectivity_sheet(data = TAB,
                           output_dir = output_dir,
                           output_file = "fiche_InseR_twin",
                           protocol = "twin",
                           language = "FR",
                           zones=zones,
                           min_length=min_length)
  
  #' @description Testing the output file from `create_selectivity_sheet()` is created
  expect_true(file.exists(file.path(output_dir, "fiche_InseR_twin.docx")))
  
  # unzip doc to access figures and tables
  unzip(file.path(output_dir, "fiche_InseR_twin.docx"), exdir = file.path(output_dir, "unzip_out"))
  
  # list of expect files
  expected_figures <- c("rId100.png", "rId104.png", "rId107.png", "rId110.png", "rId113.png",
    "rId116.png", "rId119.png", "rId22.png", "rId26.png", "rId29.png",
    "rId32.png", "rId35.png", "rId38.png", "rId41.png", "rId44.png",
    "rId51.png", "rId56.png", "rId63.png", "rId66.png", "rId69.png",
    "rId72.png", "rId75.png", "rId78.png", "rId85.png", "rId88.png",
    "rId91.png", "rId94.png", "rId97.png")

  #' @description Testing all figures in the sheet are created
  expect_setequal(object = list.files(file.path(output_dir,
                                                "unzip_out",
                                                "word",
                                                "media")),
                  expected = expected_figures)
  
  #' @description Testing all the figures in the sheet are visually correct
  purrr::walk(.x = expected_figures,
              .f = \(x) expect_snapshot_file(path = file.path(
                output_dir,
                "unzip_out",
                "word",
                "media",
                x
              ),
              x))
  
  # Clear tmp folder
  unlink(output_dir, recursive = TRUE)
})
