# WARNING - Generated by {fusen} from /dev/flat_utils.Rmd: do not edit by hand

test_that("f_test works", {

  # Create tmp folder
  output_dir <- tempfile(pattern = "inser")
  dir.create(output_dir)
  
  # Setup input OTT data
  OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
  
  TR <- readr::read_delim(
    file = file.path(OTT_data_folder, "TR.csv"),
    delim = ";",
    escape_double = FALSE,
    locale = readr::locale(encoding = "WINDOWS-1252"),
    trim_ws = TRUE
  )
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")#,colClasses = colClasses)
  
  SL<-read.table(
    file.path(OTT_data_folder, "SL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  HL<-read.table(
    file.path(OTT_data_folder, "HL.csv"),
    sep=";",
    header=TRUE,
    encoding = "WINDOWS-1252")
  
  colClasses<-rep(NA,ncol(HH))
  colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
  
  HH<-read.table(
    file.path(OTT_data_folder, "HH.csv"),
    sep=";",
    header=TRUE,
    colClasses = colClasses,
    encoding = "WINDOWS-1252")
  
  # create selectivity data object
  data <- prep_sel_data(data=list(TR,HH,SL,HL))
  
  # extract weight data per species
  weight_species <- data %>%
    dplyr::group_by(
      project,
      vessel_identifier,
      trip_code,
      station_number,
      gear_label,
      catch_category,
      species
    ) %>%
    dplyr::summarize(weight = sum(weight) * 10 ^ (-3)) %>%
    as.data.frame()
  
  weight_species <- as.data.frame(tidyr::complete(
    weight_species,
    tidyr::nesting(project, vessel_identifier, trip_code, station_number),
    gear_label,
    catch_category,
    species,
    fill = list(weight = 0)
  ))
  
  tab_diff <- weight_species %>% dplyr::group_by(project,
                                          vessel_identifier,
                                          trip_code,
                                          station_number,
                                          catch_category,
                                          species) %>%
    dplyr::summarize(
      diff_weight = weight[gear_label == "TEST"] - weight[gear_label == "STD"],
      weight_STD = weight[gear_label == "STD"],
      weight_TEST = weight[gear_label == "TEST"]
    )
  
  # run f_test
  ftest_solea_solea <- f_test(tab_diff = tab_diff,
        sp = "Solea solea",
        cat = "LAN")
  
  
  #' @description Test f_test return teh correct statistical values
  expect_equal(object = ftest_solea_solea,
               expected = structure(
                 list(
                   pvalue = 0.1283,
                   moyenne = -101.11430697482,
                   mediane = -50.1763443039034,
                   test = "Fisher",
                   Taux_Var_Tot = -82.21,
                   Taux_Var_OP = -70.44
                 ),
                 class = "data.frame",
                 row.names = c(NA, -1L)
               ))
  
  # Clear tmp folder
  unlink(output_dir, recursive = TRUE)
})
