# WARNING - Generated by {fusen} from /dev/flat_create_maps.Rmd: do not edit by hand

#' create_maps
#'
#' @inheritParams create_selectivity_sheet
#' @param ices_data sp object The spatial polygon data.frame of the study area
#' 
#' @importFrom dplyr group_by summarize mutate filter select
#' @importFrom ggplot2 ggplot coord_quickmap theme_light theme element_text annotation_map 
#' @importFrom ggplot2 map_data aes geom_text geom_rect coord_sf theme_classic labs
#' @importFrom ggplot2 element_rect geom_line arrow unit guides xlab ylab labs geom_sf
#' @importFrom ggpubr ggarrange
#' @importFrom sf st_set_agr st_centroid st_drop_geometry st_bbox
#' @importFrom purrr map
#' @importFrom stringr str_c
#'
#' @return ggplot A ggplot object of the map and zoom graphs
#' @noRd
#' @examples
#' # Setup input OTT data
#' OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
#' 
#' TR <- readr::read_delim(
#'   file = file.path(OTT_data_folder, "TR.csv"),
#'   delim = ";",
#'   escape_double = FALSE,
#'   locale = readr::locale(encoding = "WINDOWS-1252"),
#'   trim_ws = TRUE
#' )
#' 
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")#,colClasses = colClasses)
#' 
#' SL<-read.table(
#'   file.path(OTT_data_folder, "SL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#' 
#' HL<-read.table(
#'   file.path(OTT_data_folder, "HL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#' 
#' colClasses<-rep(NA,ncol(HH))
#' colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
#' 
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   colClasses = colClasses,
#'   encoding = "WINDOWS-1252")
#' 
#' # create TAB output
#' TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
#' 
#' # create maps
#' output <- create_maps(
#'   zones = c("8.a","8.b","7.d","7.e","7.h"),
#'   protocol = "twin",
#'   data = TAB
#' )
#' output
create_maps <- function(
    data,
    zones = NULL,
    protocol,
    ices_data = readRDS(
      file = system.file("ices_data_sf.rds", package = "inser")
    )
){
  
  ## Create two maps: Map and Zoom
  
  ## Map ----
  
  if(!is.null(zones)) {
    target_polygones_sf <- ices_data %>%
      mutate(
        area = paste(SubArea, Division, sep = ".")
      ) %>%
      filter(
        area %in% zones
      )
  } else {
    target_polygones_sf <- ices_data
  }
  
  ICESp <- ggplot() +
    coord_quickmap() +
    theme_light() +
    theme(
      axis.text = element_text(size = 18),
      axis.title = element_text(size = 20)
    ) +
    annotation_map(
      map = map_data("world"),
      alpha = 0.5,
      fill = "grey",
      col = "white"
    ) + #Add the map as a base layer before the points
    geom_sf(
      data = target_polygones_sf,
      alpha = 0.5,
      fill = "#69b3a2",
      color = "white"
    ) +
    labs(
      x = "long",
      y = "lat"
    )
  
  df_ICES <- target_polygones_sf %>%
    select(
      geometry,
      name = area
    ) %>%
    st_set_agr("constant") %>%
    st_centroid() %>%
    mutate(
      x = as.numeric(purrr::map(geometry, 1)),
      y = as.numeric(purrr::map(geometry, 2))
    ) %>%
    st_drop_geometry()
  
  
  bbox_target_polygones_sf <- st_bbox(target_polygones_sf)
  
  lon_min <- floor(bbox_target_polygones_sf["xmin"])
  lon_max <- ceiling(bbox_target_polygones_sf["xmax"])
  lat_min <- floor(bbox_target_polygones_sf["ymin"])
  lat_max <- ceiling(bbox_target_polygones_sf["ymax"])
  by_lat <- round((lat_max - lat_min) / 5)
  by_lon <- round((lon_max - lon_min) / 5)
  
  rangeX <- with(data, abs(
    min(pos_start_lon_dec, pos_stop_lon_dec) - max(pos_start_lon_dec, pos_stop_lon_dec)
  ))
  rangeY <- with(data, abs(
    min(pos_start_lat_dec, pos_stop_lat_dec) - max(pos_start_lat_dec, pos_stop_lat_dec)
  ))
  xlim = with(data, c(
    min(pos_start_lon_dec, pos_stop_lon_dec) - 0.15 * rangeX,
    max(pos_start_lon_dec, pos_stop_lon_dec) + 0.15 * rangeX
  ))
  ylim = with(data, c(
    min(pos_start_lat_dec, pos_stop_lat_dec) - 0.15 * rangeY,
    max(pos_start_lat_dec, pos_stop_lat_dec) + 0.15 * rangeY
  ))
  
  
  Map <- ICESp +
    geom_text(
      data = df_ICES,
      aes(x = x, y = y, label = name),
      col = "white",
      fontface = 3
    ) +
    geom_rect(
      mapping = aes(
        xmin = xlim[1],
        xmax = xlim[2],
        ymin = ylim[1],
        ymax = ylim[2]
      ),
      fill = NA,
      colour = "#1b98e0",
      linewidth = 1
    ) 
  
  ## Zoom ----
  
  PosX <- seq(floor(xlim[1]), ceiling(xlim[2]), 5 / 60)
  Deg <- ceiling(PosX)
  Min <- round((Deg - PosX) * 60)
  LabX <- str_c(Deg, "\u00b0", Min, "\'W")
  idX <- which(PosX >= xlim[1]  & PosX <= xlim[2])
  
  PosY <- seq(floor(ylim[1]), ceiling(ylim[2]), 5 / 60)
  Deg <- floor(PosY)
  Min <- round((PosY - Deg) * 60)
  LabY <- str_c(Deg, "\u00b0", Min, "\'N")
  idY <- which(PosY >= ylim[1]  & PosY <= ylim[2])
  
  if (protocol == "twin") {
    Pos_Start <- data %>%
      group_by(project,
               vessel_identifier, trip_code, station_number) %>%
      summarize(Lat = unique(pos_start_lat_dec),
                Lon = unique(pos_start_lon_dec))
    Pos_Start$order <- "start"
    Pos_Stop <- data %>%
      group_by(project, vessel_identifier, trip_code, station_number) %>%
      summarize(Lat = unique(pos_stop_lat_dec),
                Lon = unique(pos_stop_lon_dec))
    Pos_Stop$order <- "end"
    Pos_Station <- rbind(Pos_Start, Pos_Stop)
    Pos_Station$id_station <- with(
      Pos_Station,
      paste(project, vessel_identifier, trip_code, station_number)
    )
    
    Zoom <- ggplot() +
      coord_quickmap() +
      theme_classic() +
      theme(
        panel.border = element_rect(
          color = "#1b98e0",
          fill = NA,
          linewidth = 3
        )
      ) +
      annotation_map(
        map = map_data("world"),
        alpha = 0.5,
        fill = "grey",
        col = "white"
      ) +
      geom_sf(
        data = target_polygones_sf,
        alpha = 0.2,
        fill = "#69b3a2",
        color = "white"
      ) +
      labs(
        x = "long",
        y = "lat"
      ) +
      geom_text(
        data = df_ICES,
        aes(x = x, y = y, label = name),
        col = "white",
        fontface = 3
      ) +
      coord_sf(
        xlim = xlim,
        ylim = ylim,
        expand = FALSE
      ) +
      geom_line(
        data = Pos_Station,
        aes(group = id_station, x = Lon, y = Lat),
        color = "grey",
        arrow = arrow(type = "closed", length = unit(0.075, "inches"))
      )
  }
  
  if (protocol == "paired") {
    Pos_Start <- data %>% group_by(
      project,
      vessel_identifier,
      trip_code,
      tag_operation,
      station_number,
      gear_label
    ) %>%
      summarize(Lat = unique(pos_start_lat_dec),
                Lon = unique(pos_start_lon_dec))
    Pos_Start$order <- "start"
    Pos_Stop <-
      data %>% group_by(project,
                        vessel_identifier,
                        trip_code,
                        tag_operation,
                        station_number,
                        gear_label) %>%
      summarize(Lat = unique(pos_stop_lat_dec),
                Lon = unique(pos_stop_lon_dec))
    Pos_Stop$order <- "end"
    Pos_Station <- rbind(Pos_Start, Pos_Stop)
    Pos_Station$id_station <-
      with(
        Pos_Station,
        paste(
          project,
          vessel_identifier,
          trip_code,
          tag_operation,
          station_number
        )
      )
    
    Zoom <- ggplot() + coord_quickmap() + theme_classic() +
      theme(
        legend.position = "bottom",
        panel.border = element_rect(
          color = "#1b98e0",
          fill = NA,
          linewidth = 3
        )
      ) +
      guides(col = FALSE)  +
      xlab("") + ylab("") +
      labs(linetype = "Engin") +
      annotation_map(map_data("world"),
                     alpha = 0.5,
                     fill = "grey",
                     col = "white") + #Add the map as a base layer before the points
      geom_sf(
        data = target_polygones_sf,
        alpha = 0.2,
        fill = "#69b3a2",
        color = "white"
      ) +
      labs(
        x = "long",
        y = "lat"
      ) +
      geom_text(
        data = df_ICES,
        aes(x = x, y = y, label = name),
        col = "white",
        fontface = 3
      ) +
      coord_sf(
        xlim = xlim,
        ylim = ylim,
        expand = TRUE
      ) +
      geom_line(
        data = Pos_Station,
        aes(
          group = id_station,
          x = Lon,
          y = Lat,
          color = as.factor(tag_operation),
          linetype = gear_label
        ),
        arrow = arrow(type = "closed", length = unit(0.075, "inches"))
      )
  }
  
  if (protocol == "unpaired") {
    Pos_Start <-
      data %>% group_by(project,
                        vessel_identifier,
                        trip_code,
                        station_number,
                        gear_label) %>%
      summarize(Lat = unique(pos_start_lat_dec),
                Lon = unique(pos_start_lon_dec))
    Pos_Start$order <- "start"
    Pos_Stop <-
      data %>% group_by(project,
                        vessel_identifier,
                        trip_code,
                        station_number,
                        gear_label) %>%
      summarize(Lat = unique(pos_stop_lat_dec),
                Lon = unique(pos_stop_lon_dec))
    Pos_Stop$order <- "end"
    Pos_Station <- rbind(Pos_Start, Pos_Stop)
    Pos_Station$id_station <-
      with(Pos_Station,
           paste(project, vessel_identifier, trip_code, station_number))
    
    Zoom <- ggplot() + coord_quickmap() + theme_classic() +
      theme(
        legend.position = "bottom",
        axis.text = element_text(size = 18),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 18),
        panel.border = element_rect(
          color = "#1b98e0",
          fill = NA,
          linewidth = 3
        )
      ) +
      guides(col = FALSE)  +
      xlab("") + ylab("") +
      labs(linetype = "Engin") +
      annotation_map(map_data("world"),
                     alpha = 0.5,
                     fill = "grey",
                     col = "white") + #Add the map as a base layer before the points
      geom_sf(
        data = target_polygones_sf,
        alpha = 0.2,
        fill = "#69b3a2",
        color = "white"
      ) +
      labs(
        x = "long",
        y = "lat"
      ) +
      geom_text(
        data = df_ICES,
        aes(x = x, y = y, label = name),
        col = "white",
        fontface = 3
      ) +
      coord_sf(
        xlim = xlim,
        ylim = ylim,
        expand = TRUE
      ) +
      geom_line(
        data = Pos_Station,
        aes(
          group = id_station,
          x = Lon,
          y = Lat,
          color = as.factor(trip_code),
          linetype = gear_label
        ),
        arrow = arrow(type = "closed", length = unit(0.075, "inches"))
      )
  }
  
  Maps <- ggarrange(Map, Zoom)
  Maps
  
  return(Maps)
}
