# WARNING - Generated by {fusen} from /dev/flat_create_selectivity_sheet.Rmd: do not edit by hand

#' create_selectivity_sheet Title
#'
#' @description GÃ©nÃ¨re une fiche synthÃ©tique dÃ©crivant les donnÃ©es et contenant 
#' un ensemble dâ€™indicateurs de sÃ©lectivitÃ©. 
#' 
#' @param data data.frame A dataframe as generated by prep_sel_data() 
#' @param protocol character Type of protocol. â€œtwinâ€ for experiment where both fishing gear are deployed in the same fishing operation (e.g. using twin trawls) ; â€œpairedâ€ for experiment where the two fishing gear are deployed in a set of â€˜pairsâ€™ : two different fishing operations, but in very similar conditions; â€œunpairedâ€ for experiment where the gear are tested independently in two different samples of fishing operations.
#' @param output_dir character Directory name where the sheet should be written
#' @param output_file character Name of the file for the sheet
#' @param min_length numeric Optional. For species analyzed in length, the minimum targeted length for selectivity (e.g., MCRS) for graphics and statistics. A data.frame with a column â€˜speciesâ€™ and a column â€˜min_lengthâ€™ for the corresponding minimum length.
#' @param language character English by default (â€œENâ€). Can be passed in French (â€œFRâ€).
#' @param zones character The vector of zones used in the report.
#'
#' @importFrom rmarkdown render
#  imports within Rmd templates
#' @importFrom dplyr group_by summarise summarize select filter bind_rows
#' @importFrom knitr kable
#' @importFrom ggplot2 ggplot aes geom_boxplot geom_point theme xlab element_text element_blank labs stat_summary position_dodge theme_light scale_x_discrete xlim ylim  geom_bar geom_vline geom_hline guides ggtitle guide_legend
#' @importFrom ggpubr ggarrange
#' @importFrom stats shapiro.test t.test wilcox.test
#' @importFrom tidyr complete nesting
#' 
#' @return None A Word document is generated in the output_dir as well as all the figures in png.
#' For more details on the selectivity sheet format, see the related vignette :
#' \code{vignette("create-selectivity-sheet", package = "inser")}
#' @export
#'
#' @examples
#' # Create tmp folder
#' output_dir <- tempfile(pattern = "inser")
#' dir.create(output_dir)
#' 
#' # Setup input OTT data
#' OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
#' 
#' TR <- readr::read_delim(
#'   file = file.path(OTT_data_folder, "TR.csv"),
#'   delim = ";",
#'   escape_double = FALSE,
#'   locale = readr::locale(encoding = "WINDOWS-1252"),
#'   trim_ws = TRUE
#' )
#' 
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")#,colClasses = colClasses)
#' 
#' SL<-read.table(
#'   file.path(OTT_data_folder, "SL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#' 
#' HL<-read.table(
#'   file.path(OTT_data_folder, "HL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#' 
#' colClasses<-rep(NA,ncol(HH))
#' colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
#' 
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   colClasses = colClasses,
#'   encoding = "WINDOWS-1252")
#' 
#' # create TAB output
#' TAB <- prep_sel_data(data=list(TR,HH,SL,HL))
#' 
#' # Setup zone and min_length params
#' min_length <- data.frame(species=unique(TAB$species),min_length=c(27,24,20,NA,27,NA))
#' zones <- c("8.a","8.b","7.d","7.e","7.h")
#' 
#' # run function
#' create_selectivity_sheet(data = TAB,
#'                          output_dir = output_dir,
#'                          output_file = "fiche_InseR_twin",
#'                          protocol = "twin",
#'                          language = "FR",
#'                          zones=zones,
#'                          min_length=min_length)
#' 
#' # Clear tmp folder
#' unlink(output_dir, recursive = TRUE)
create_selectivity_sheet <- function(
    data,
    protocol,
    output_dir = NULL,
    output_file = NULL,
    min_length = NULL,
    language = "EN",
    zones
) {
  
  # Check argumetns protocol and language were provided with legible values
  protocol <- match.arg(
    arg = protocol, 
    choices = c("twin", "paired", "unpaired")
  )
  language <- match.arg(
    arg = language, 
    choices = c("FR", "EN")
  )
  
  #How to make by default the same parameters as in the render() function?
  
  ##Control function parameters?
  
  ##Mapping : A mettre dans le Rmd? (comme scripts Rmd sÃ©parÃ©s par language + protocol, 
  ##Comment faire si ni zones ni area sont renseignÃ©es ?
  
  Maps <- create_maps(
    data = data, 
    zones = zones,
    protocol = protocol
  )
  
  # Setup template report path
  path_templates <- system.file("template", package = "inser")
  
  # Setup language translation object
  lg <- create_translate_dict(
    path = system.file("template", "translation_2_utf8.csv", package = "inser"),
    language = language
  )
  
  path_template_rmd <- file.path(
    path_templates,
    sprintf(
      "selectivity_sheet_%s.Rmd",
      protocol
    )
  )
  
  render(
    input = path_template_rmd,
    output_dir = output_dir,
    output_file = output_file,
    params = list(lg = lg)
  )
  
}
