# WARNING - Generated by {fusen} from /dev/flat_translate_selectivity_sheet.Rmd: do not edit by hand

#' create_translate_dict
#' 
#' Create a list with all the text elements of the selectivity sheet in the selected language
#'
#' @param path character. The path to the csv translation file
#' @param language character. The chosen language for the text, must be "FR" or "EN" (default)
#' @param encoding character. The encoding of the csv file, default to "UTF-8"
#' @param sep character. The field separator used in the CSV file
#' 
#' @importFrom glue glue
#' @importFrom tools file_ext
#' @importFrom stats setNames
#' @importFrom utils read.csv
#' 
#' @return list. A list of translated text, with names referring to their location in the sheet
#' @export
#' @examples
#' # create the EN translator
#' lg <- create_translate_dict(language = "EN")
#' 
#' # call main title by its ID
#' cat(lg[["0_main_title"]])
#' 
#' # create the FR translator
#' lg <- create_translate_dict(language = "FR")
#' 
#' # call main title by its ID
#' cat(lg[["0_main_title"]])
create_translate_dict <- function(path = system.file("template", "translation.csv", package = "inser"),
                                  language = c("EN", "FR"),
                                  encoding = "UTF-8",
                                  sep = ";") {
  # check selected language
  language <- match.arg(language)
  
  # check translation file exist
  if (isFALSE(file.exists(path))) {
    stop(glue("Translation file {path} not found"))
  }
  
  # check if translation file is a csv
  if (isTRUE(file_ext(path) != "csv")) {
    stop(glue("Translation file {path} is not a csv file"))
  }
  
  # read csv and extract language as named list
  translator <- read.csv(file = path,
                         encoding = encoding,
                         sep = sep)
  
  translator <- setNames(object = translator[[language]],
                         nm = as.character(translator[["id"]])
                         )
  
  # warn user of the translation being used
  message(glue("Using the {language} version of the selectivity template"))
  
  # return list
  return(translator)
}
