# WARNING - Generated by {fusen} from /dev/flat_utils.Rmd: do not edit by hand

#' f_test_paired
#'
#' @description Computes the paired tests on difference in weight per catch category
#'
#' @param tab_diff data.frame. A dataframe containing the computed differences in weight between TEST and STD device per catch category
#' @param sp character. The species to use in test
#' @param cat character. The category to use in test
#'
#' @importFrom dplyr filter
#' @importFrom stats shapiro.test t.test wilcox.test
#' @importFrom stats median
#'
#' @return data.frame. The summary table of the statistical tests
#' @export
#' @examples
#' # Create tmp folder
#' output_dir <- tempfile(pattern = "inser")
#' dir.create(output_dir)
#'
#' # Setup input OTT data
#' OTT_data_folder <- system.file("script_origin","Data","Example_OTT", package = "inser")
#'
#' TR <- readr::read_delim(
#'   file = file.path(OTT_data_folder, "TR.csv"),
#'   delim = ";",
#'   escape_double = FALSE,
#'   locale = readr::locale(encoding = "WINDOWS-1252"),
#'   trim_ws = TRUE
#' )
#'
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")#,colClasses = colClasses)
#'
#' SL<-read.table(
#'   file.path(OTT_data_folder, "SL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#'
#' HL<-read.table(
#'   file.path(OTT_data_folder, "HL.csv"),
#'   sep=";",
#'   header=TRUE,
#'   encoding = "WINDOWS-1252")
#'
#' colClasses<-rep(NA,ncol(HH))
#' colClasses[which(names(HH)=="statistical_rectangle")]<-"character"
#'
#' HH<-read.table(
#'   file.path(OTT_data_folder, "HH.csv"),
#'   sep=";",
#'   header=TRUE,
#'   colClasses = colClasses,
#'   encoding = "WINDOWS-1252")
#'
#' # create selectivity data object
#' data <- prep_sel_data(data=list(TR,HH,SL,HL))
#'
#' # extract weight data per species
#' weight_species <- data %>%
#'   dplyr::group_by(
#'     project,
#'     vessel_identifier,
#'     trip_code,
#'     station_number,
#'     gear_label,
#'     catch_category,
#'     species
#'   ) %>%
#'   dplyr::summarize(weight = sum(weight) * 10 ^ (-3)) %>%
#'   as.data.frame()
#'
#' weight_species <- as.data.frame(tidyr::complete(
#'   weight_species,
#'   tidyr::nesting(project, vessel_identifier, trip_code, station_number),
#'   gear_label,
#'   catch_category,
#'   species,
#'   fill = list(weight = 0)
#' ))
#'
#' tab_diff <- weight_species %>% dplyr::group_by(project,
#'                                                vessel_identifier,
#'                                                trip_code,
#'                                                station_number,
#'                                                catch_category,
#'                                                species) %>%
#'   dplyr::summarize(
#'     diff_weight = weight[gear_label == "TEST"] - weight[gear_label == "STD"],
#'     weight_STD = weight[gear_label == "STD"],
#'     weight_TEST = weight[gear_label == "TEST"]
#'   )
#'
#' # run f_test
#' f_test_paired(tab_diff = tab_diff,
#'        sp = "Solea solea",
#'        cat = "LAN")
#'
#' # Clear tmp folder
#' unlink(output_dir, recursive = TRUE)
f_test_paired <- function(tab_diff,
                   sp,
                   cat
                   ) {

  # weight differences of the cat fraction by species sp pairs
  Diff_sp <- tab_diff %>%
    filter(species == sp & catch_category == cat)

  #1.Normality test (Shapiro-Wilk)
  test1 <- tryCatch(
    expr = shapiro.test(x = Diff_sp[["diff_weight"]]),
    error = function(e) {
      "e"
    }
  )

  if (inherits(test1, "htest")) {
    # If normality is not rejected (Shapiro p-value > 0.05), Student t.test :
    if (test1$p.value > 0.05) {
      test2 <- tryCatch(
        expr = t.test(x = Diff_sp[["diff_weight"]],
                      mu = 0),
        error = function(e) {
          "e"
        }
      )
    }

    # If normality is rejected (Shapiro p-value <= 0.05), Mann-Whitney/Wilcoxon test :
    if (test1$p.value <= 0.05) {
      test2 <- tryCatch(
        expr = wilcox.test(
          x = Diff_sp[["diff_weight"]],
          paired = FALSE,
          correct = TRUE,
          exact = FALSE
        ),
        error = function(e) {
          "e"
        }
      )
    }

    ## Results of Student/Wilcoxon tests :
    if (test1$p.value <= 0.05) {
      tab_test <- data.frame(
        pvalue = round(test2[["p.value"]], 4),
        moyenne = mean(Diff_sp[["diff_weight"]]),
        mediane = median(Diff_sp[["diff_weight"]]),
        test = "Wilcoxon"
      )
    }

    if (test1[["p.value"]] > 0.05) {
      tab_test <- data.frame(
        pvalue = round(test2[["p.value"]], 4),
        moyenne = mean(Diff_sp[["diff_weight"]]),
        mediane = median(Diff_sp[["diff_weight"]]),
        test = "Fisher"
      )
    }

  } else{
    tab_test <- data.frame(
      pvalue = NA,
      moyenne = mean(Diff_sp[["diff_weight"]]),
      mediane = median(Diff_sp[["diff_weight"]]),
      test = NA
    )
  }


  # Variation rate of landing weights from TEST compared to STD
  Tot_TEST <- sum(Diff_sp[["weight_TEST"]])
  Tot_STD <- sum(Diff_sp[["weight_STD"]])

  Taux_sp <- round(100 * (Tot_TEST - Tot_STD) / Tot_STD, 2) # pooling all the fishing operation together

  Var_Rate2 <- with(Diff_sp, diff_weight / weight_STD) * 100
  Taux_sp_OP <- round(mean(Var_Rate2, na.rm = T), 2)# mean by OP")

  tab_test <- data.frame(tab_test,
                         Taux_Var_Tot = Taux_sp,
                         Taux_Var_OP = Taux_sp_OP)
  return(tab_test)
}
