globalVariables(unique(
  c(
    # prep_sel_data:
    "catch_category",
    "fishing_validity",
    "project",
    "species",
    "station_number",
    "trip_code",
    "vessel_identifier",
    # create_maps:
    "gear_label",
    "group",
    "id_station",
    "lat",
    "Lat",
    "Lon",
    "long",
    "name",
    "pos_start_lat_dec",
    "pos_start_lon_dec",
    "pos_stop_lat_dec",
    "pos_stop_lon_dec",
    "tag_operation",
    "x",
    "y",
    "Division",
    "SubArea",
    "area",
    "geometry"
  )
))
